"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";
import { BrainCircuit, CheckCircle2, Clock3, Download, FileAudio, LockKeyhole, MessageSquareText, Sparkles, Trash2, UploadCloud } from "lucide-react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://127.0.0.1:8000";
type ActionItem={task:string;owner:string|null;deadline:string|null}; type Analysis={title:string;summary:string;key_points:string[];action_items:ActionItem[]}; type Meeting={id:string;filename:string;created_at:string;language?:string|null;duration?:number|null;transcript?:string|null;analysis?:Analysis|null}; type Timings={transcription?:number;analysis?:number;total?:number};
export default function Home(){
 const inputRef=useRef<HTMLInputElement>(null); const[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[stage,setStage]=useState(0),[activeStep,setActiveStep]=useState("Ready"),[meeting,setMeeting]=useState<Meeting|null>(null),[history,setHistory]=useState<Meeting[]>([]),[question,setQuestion]=useState(""),[answer,setAnswer]=useState(""),[error,setError]=useState(""),[timings,setTimings]=useState<Timings>({});
 async function loadHistory(){try{const r=await fetch(`${API}/meetings`);if(r.ok)setHistory(await r.json())}catch{}} useEffect(()=>{loadHistory()},[]);
 function chooseFile(e:ChangeEvent<HTMLInputElement>){setFile(e.target.files?.[0]||null);setError("");setStage(0);setTimings({})}
 async function processRecording(){if(!file)return;setBusy(true);setError("");setAnswer("");setStage(0);setTimings({});const start=performance.now();try{setActiveStep("Uploading recording…");const form=new FormData();form.append("file",file);const u=await fetch(`${API}/meetings/upload`,{method:"POST",body:form});if(!u.ok)throw new Error("Upload failed");const ud=await u.json();setStage(1);setActiveStep("Transcribing with Whisper…");const tr=await fetch(`${API}/meetings/${ud.meeting_id}/transcribe`,{method:"POST"}),td=await tr.json();if(!tr.ok)throw new Error(td.detail||"Transcription failed");setTimings(t=>({...t,transcription:td.processing_seconds}));setStage(2);setActiveStep("Analyzing locally with Ollama…");const ar=await fetch(`${API}/meetings/${ud.meeting_id}/analyze`,{method:"POST"}),ad=await ar.json();if(!ar.ok)throw new Error(ad.detail||"AI analysis failed");setTimings(t=>({...t,analysis:ad.processing_seconds}));setStage(3);setActiveStep("Complete");const d=await fetch(`${API}/meetings/${ud.meeting_id}`);setMeeting(await d.json());setTimings(t=>({...t,total:(performance.now()-start)/1000}));await loadHistory()}catch(e){setActiveStep("Failed");setError(e instanceof Error?e.message:"Something went wrong")}finally{setBusy(false)}}
 async function openMeeting(id:string){setAnswer("");const r=await fetch(`${API}/meetings/${id}`);if(r.ok)setMeeting(await r.json())}
 async function ask(){if(!meeting||!question.trim())return;setBusy(true);setError("");setAnswer("");try{const r=await fetch(`${API}/meetings/${meeting.id}/ask`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question})}),d=await r.json();if(!r.ok)throw new Error(d.detail||"Q&A failed");setAnswer(d.answer)}catch(e){setError(e instanceof Error?e.message:"Q&A failed")}finally{setBusy(false)}}
 async function remove(id:string){if(!window.confirm("Delete this meeting and its local files?"))return;const r=await fetch(`${API}/meetings/${id}`,{method:"DELETE"});if(r.ok){if(meeting?.id===id)setMeeting(null);await loadHistory()}}
 async function clearAll(){if(!window.confirm("Delete all meeting history and local recordings?"))return;const r=await fetch(`${API}/meetings`,{method:"DELETE"});if(r.ok){setMeeting(null);setHistory([])}}
 function saveFile(name:string,text:string){const blob=new Blob([text],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
 function exportNotes(){if(!meeting)return;const a=meeting.analysis;saveFile("meeting-notes.md",`# ${a?.title||meeting.filename}\n\n## Summary\n${a?.summary||""}\n\n## Key Points\n${(a?.key_points||[]).map(x=>`- ${x}`).join("\n")}\n\n## Action Items\n${(a?.action_items||[]).map(x=>`- ${x.task}`).join("\n")||"No explicit action items."}\n\n## Transcript\n${meeting.transcript||""}`)}
 const fmt=(n?:number)=>n==null?"—":`${n.toFixed(1)}s`;
 return <main className="shell"><div className="container"><header className="header"><div className="brand"><div className="logo"><BrainCircuit size={21}/></div>AI Meeting Assistant</div><div className="badge"><LockKeyhole size={12}/> Local AI · Privacy First</div></header><section className="hero"><div className="eyebrow">Whisper + Ollama + FastAPI</div><h1>Turn conversations into useful knowledge.</h1><p>Upload a meeting or lecture recording. Local AI transcribes it, extracts the essentials and lets you ask grounded questions.</p></section><section className="grid">
 <article className="card"><h2>Process a recording</h2><p>MP3, WAV, M4A, MP4, WebM or OGG.</p><div className="drop" onClick={()=>!busy&&inputRef.current?.click()}><div><div className="dropIcon"><UploadCloud/></div><strong>{file?file.name:"Choose a recording"}</strong><p className="muted">Click to select an audio or video file</p></div></div><input ref={inputRef} className="fileInput" type="file" accept="audio/*,video/mp4,video/webm" onChange={chooseFile}/><div className="actionRow"><span className="muted">Runs locally on your machine</span><button className="primary" disabled={!file||busy} onClick={processRecording}>{busy?activeStep:"Transcribe & Analyze"}</button></div><div className="status">{["1 Upload","2 Whisper","3 AI Analysis"].map((x,i)=><span key={x} className={`pill ${stage>i?"done":""}`}>{stage>i&&<CheckCircle2 size={12}/>} {x}</span>)}</div>{(busy||timings.total)&&<div className="timingBar"><Clock3 size={14}/><span>{activeStep}</span><b>Total {fmt(timings.total)}</b><span>Whisper {fmt(timings.transcription)}</span><span>AI {fmt(timings.analysis)}</span></div>}{error&&<div className="error">{error}</div>}</article>
 <aside className="card"><div className="sectionHead"><div><h2>Meeting history</h2><p>Your locally stored recordings and analyses.</p></div>{history.length>0&&<button className="iconButton" onClick={clearAll} title="Clear history"><Trash2 size={16}/></button>}</div><div className="history">{history.length===0?<div className="muted">No meetings yet.</div>:history.slice(0,10).map(m=><div className="historyWrap" key={m.id}><button className="historyItem" onClick={()=>openMeeting(m.id)}><strong>{m.analysis?.title||m.filename}</strong><small>{m.filename} · {m.language||"—"}{m.duration?` · ${Math.round(m.duration)}s`:""}</small></button><button className="deleteMini" onClick={()=>remove(m.id)}><Trash2 size={14}/></button></div>)}</div></aside>
 {meeting&&<article className="card result"><div className="resultHeader"><div className="resultTitle"><div className="dropIcon compact"><FileAudio size={20}/></div><div><h2>{meeting.analysis?.title||meeting.filename}</h2><span className="muted">{meeting.filename} · {meeting.language||"unknown"}{meeting.duration?` · ${Math.round(meeting.duration)}s`:""}</span></div></div><div className="exportRow"><button className="secondary" onClick={()=>saveFile("transcript.txt",meeting.transcript||"")}><Download size={14}/> Transcript</button><button className="secondary" onClick={exportNotes}><Download size={14}/> Notes</button></div></div><div className="resultGrid"><section className="panel"><h3><Sparkles size={15}/> AI Summary</h3><p>{meeting.analysis?.summary||"No analysis yet."}</p></section><section className="panel"><h3>Key Points</h3><ul>{meeting.analysis?.key_points?.map((x,i)=><li key={i}>{x}</li>)}</ul></section><section className="panel"><h3>Action Items</h3>{meeting.analysis?.action_items?.length?<div className="actions">{meeting.analysis.action_items.map((x,i)=><div className="actionCard" key={i}><b>{x.task}</b>{(x.owner||x.deadline)&&<small>{x.owner||"Unassigned"}{x.deadline?` · ${x.deadline}`:""}</small>}</div>)}</div>:<p className="muted">No explicit action items detected.</p>}</section><section className="panel"><h3>Transcript</h3><div className="transcript">{meeting.transcript||"No transcript available."}</div></section></div><section className="panel qa"><h3><MessageSquareText size={15}/> Ask this meeting</h3><p className="muted">Grounded in this transcript only.</p><div className="ask"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder="What decisions were made?"/><button className="primary" disabled={busy||!question.trim()} onClick={ask}>{busy?"Thinking…":"Ask AI"}</button></div>{answer&&<div className="answer">{answer}</div>}</section></article>}
 </section></div></main>}
